#!/bin/sh /etc/rc.common

START=93
STOP=15
PROG=/bin/vlmcsd
CONFIG=/etc/vlmcsd.ini
LOG=/var/log/vlmcsd.log

get_config()
{
	config_get_bool enable $1 enable 0
	[ $enable -eq 0 ] && exit 0
	config_get_bool use_conf_file $1 use_conf_file 0
	config_get port $1 port
}

start()
{
	config_load vlmcsd
	config_foreach get_config vlmcsd
	if [ $use_conf_file -eq 1 ]; then
		service_start $PROG -i $CONFIG
	else
		service_start $PROG -P $port
	fi
}

stop()
{
	service_stop $PROG
}
